### ISSUE TITLE
Possibly false positive with symbol 'currentHost' on TestFlight submission

### ISSUE THREAD

**Issue by itsthejb** [bitstadium/HockeySDK-iOS#168] opened 2015-06-14 13:08 UTC
Hi,

We're currently trying to iron out false positive issues on a TestFlight submission (required by Apple), and the only remaining is `currentHost`, which comes up in a grep in `CrashReporter.framework`. 

It seems like they're using an extremely indiscriminate scan for TestFlight now, since the majority of the issues are simple symbol names that happen to be named the same as those in private frameworks.

**Comment by anlinde** [comment] 2015-06-20 13:53
Is this only a warning or does it block from uploading? We haven't heard such an issue from anyone else yet.

**Comment by itsthejb** [comment] 2015-06-20 13:56
This was one of a few symbols that caused a rejection for our initial Testflight submission. There are seemingly extremely strict; for example, we had to rename method arguments in `NINetworkImageView` that were clearly false positives.

**Comment by anlinde** [comment] 2015-06-20 16:16
Do you still get these warnings or was this a one time problem?

**Comment by anlinde** [comment] 2015-06-20 16:17
Also, PLCrashReporter doesn't have a symbol names `currentHost`, and neither does our SDK. PLCR has a symbol named `currentHostInfo`, so this can't be the cause for your restriction.

**Comment by itsthejb** [comment] 2015-06-20 16:22
We had to disable Hockey for the submission. It's now been accepted. It's possible we could re-enable it now and might get through a review. Hard to say. As for the symbol - yes, that's possible. I ended up grepping the binary and derived data folders for the offending symbols until I could get it "clean". I know that this was the last symbol I had to remove, and unlinking the SDK was the only way I could succeed. We didn't try to do multiple submissions to test for the symbols - I just went aggressive since we were up against the clock.

Of course, it's hard to say anything with any certainty about the internal scanning process... I thought I should raise this, in any case.

**Comment by anlinde** [comment] 2015-06-20 17:47
I just tried a submission again and it worked flawlessly. We have thousands of customers uploading builds with our SDK every day. There is no known issue on our end and as I mentioned, the symbol you mentioned is not even anywhere in our code.

I recommend adding our SDK again :) and close this issue now.

**Closed by anlinde** 2015-06-20 17:47 UTC
