### ISSUE TITLE
Carthage Compilation Failed in Xcode 10.2 beta 3

### ISSUE THREAD

**Issue by Igor-Palaguta** [bitstadium/HockeySDK-iOS#548] opened 2019-03-12 17:34 UTC
*** Building scheme "HockeySDK Framework" in HockeySDK.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun dsymutil /Users/ipalaguta/Projects/ios-app/Carthage/Build/iOS/HockeySDK.framework/HockeySDK -o /Users/ipalaguta/Projects/ios-app/Carthage/Build/iOS/HockeySDK.framework.dSYM

**Comment by MatkovIvan** [comment] 2019-03-14 12:38
Hey @Igor-Palaguta,

Thanks for getting in touch. I've tried to reproduce it on the latest beta version of Xcode (10.2 beta 4), but without success.
Could you please share the full log or provide any details that can help us to figure out what the problem is?
Did you follow [this instruction](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-ios#carthage) for adding the SDK to your project?

Thanks,
Ivan

**Comment by newmarcel** [comment] 2019-03-18 10:42
Hi! I'm experiencing the same issue and it's easy for me to reproduce it with Xcode 10.2beta4 on multiple machines:
- create an empty folder with a `Cartfile` that contains `github "bitstadium/HockeySDK-iOS"`
- run e.g. `carthage update` _(Carthage 0.32.0)_.

Eventually:
```
Build Failed
Task failed with exit code 1:
/usr/bin/xcrun dsymutil .../Carthage/Build/iOS/HockeySDK.framework/HockeySDK -o .../Carthage/Build/iOS/HockeySDK.framework.dSYM
```

**Comment by Jamminroot** [comment] 2019-03-18 12:07
Hello, **@newmarcel**!

Thanks for contacting. I've just tried to re-create situation on a different (fresh) mac mini with Xcode ver 10.2beta4, with carthage 0.32.0, and wasn't able to reproduce error:
```
a21:HockeyAppSDK-510 DC$ cat Cartfile
github "bitstadium/HockeySDK-iOS"
a21:HockeyAppSDK-510 DC$ carthage update
*** Cloning HockeySDK-iOS
*** Checking out HockeySDK-iOS at "5.1.4"
*** xcodebuild output can be found in /var/folders/52/6rttljzn3f54kjyg4pw21qz00000gp/T/carthage-xcodebuild.9gAfXA.log
*** Downloading HockeySDK-iOS.framework binary at "Version 5.1.4"
*** Building scheme "HockeySDK Framework" in HockeySDK.xcodeproj   
```
Are you using any other carthage dependencies? Also, can you please post output of ```dsymutil -v``` command?

**Comment by newmarcel** [comment] 2019-03-18 12:45
While my main project has additional dependencies the simple example of just HockeyApp in the Cartfile already causes the error for me.

```
$ xcrun dsymutil -v
Apple LLVM version 10.0.1 (clang-1001.0.46.2)
  Optimized build.
  Default target: x86_64-apple-darwin18.2.0
  Host CPU: haswell
```
`dsymutil` seems to be the version provided by the beta.


If I manually run `dsymutil` with the command from the error, I get:
```
/usr/bin/xcrun dsymutil …/Carthage/Build/iOS/HockeySDK.framework/HockeySDK -o …/Carthage/Build/iOS/HockeySDK.framework.dSYM
LLVM ERROR: IO failure on output stream: Bad file descriptor
```
which is not encouraging because I have no clue how to deal with this. I repeated the Cartfile and carthage commands with a clean slate multiple times to confirm this is not a random error.

**Comment by MatkovIvan** [comment] 2019-03-18 16:06
Hey @newmarcel,
Finally, I've managed to reproduce it. I'm looking at what we can do from our side to fix it (perhaps it's underlying tools bug). I'll keep you posted.
Please use the stable XCode version for now.

**Comment by jdhealy** [comment] 2019-03-22 17:55
Based on success with a different framework that hit this, I was able to `carthage build --verbose --no-skip-current` with a successful `dsymutil` by patching [off this commit](https://github.com/bitstadium/HockeySDK-iOS/commit/831f7e4e6bc12b2390b5221f95bbd26b4f129478) to remove all build settings for `ARCHS` and `VALID_ARCHS`:

<details> 
<summary><strong>Patch</strong></summary>

```diff
diff --git a/Support/HockeySDK.xcodeproj/project.pbxproj b/Support/HockeySDK.xcodeproj/project.pbxproj
index 907c2d3..35ec788 100644
--- a/Support/HockeySDK.xcodeproj/project.pbxproj
+++ b/Support/HockeySDK.xcodeproj/project.pbxproj
@@ -2213,7 +2213,6 @@
 				PRODUCT_NAME = HockeySDK;
 				PUBLIC_HEADERS_FOLDER_PATH = "include/$(PRODUCT_NAME)";
 				SKIP_INSTALL = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				WATCHOS_DEPLOYMENT_TARGET = 2.0;
 			};
 			name = ReleaseCrashOnlyExtensions;
@@ -2295,7 +2294,6 @@
 		1E27E6101B74F03000192AE2 /* ReleaseCrashOnlyExtensions */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
-				"ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
 				CLANG_CXX_LIBRARY = "libc++";
 				CLANG_ENABLE_MODULES = YES;
@@ -2338,7 +2336,6 @@
 				SKIP_INSTALL = YES;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VALIDATE_PRODUCT = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				VERSIONING_SYSTEM = "apple-generic";
 				VERSION_INFO_PREFIX = "";
 			};
@@ -2406,7 +2403,6 @@
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HockeySDK TestTarget.app/HockeySDK TestTarget";
 				VALIDATE_PRODUCT = YES;
-				VALID_ARCHS = "armv7 arm64";
 			};
 			name = ReleaseCrashOnlyExtensions;
 		};
@@ -2464,7 +2460,6 @@
 				PRODUCT_NAME = HockeySDK;
 				PUBLIC_HEADERS_FOLDER_PATH = "include/$(PRODUCT_NAME)";
 				SKIP_INSTALL = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				WATCHOS_DEPLOYMENT_TARGET = 2.0;
 			};
 			name = Debug;
@@ -2491,7 +2486,6 @@
 				PRODUCT_NAME = HockeySDK;
 				PUBLIC_HEADERS_FOLDER_PATH = "include/$(PRODUCT_NAME)";
 				SKIP_INSTALL = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				WATCHOS_DEPLOYMENT_TARGET = 2.0;
 			};
 			name = ReleaseDefault;
@@ -2718,7 +2712,6 @@
 				PRODUCT_NAME = HockeySDK;
 				PUBLIC_HEADERS_FOLDER_PATH = "include/$(PRODUCT_NAME)";
 				SKIP_INSTALL = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				WATCHOS_DEPLOYMENT_TARGET = 2.0;
 			};
 			name = ReleaseCrashOnly;
@@ -2835,7 +2828,6 @@
 		1EB617531B0A30480035A986 /* Debug */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
-				"ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
 				CLANG_CXX_LIBRARY = "libc++";
 				CLANG_ENABLE_MODULES = YES;
@@ -2875,7 +2867,6 @@
 				PRODUCT_NAME = HockeySDK;
 				SKIP_INSTALL = YES;
 				TARGETED_DEVICE_FAMILY = "1,2";
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				VERSIONING_SYSTEM = "apple-generic";
 				VERSION_INFO_PREFIX = "";
 			};
@@ -2884,7 +2875,6 @@
 		1EB617551B0A30480035A986 /* ReleaseDefault */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
-				"ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
 				CLANG_CXX_LIBRARY = "libc++";
 				CLANG_ENABLE_MODULES = YES;
@@ -2926,7 +2916,6 @@
 				SKIP_INSTALL = YES;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VALIDATE_PRODUCT = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				VERSIONING_SYSTEM = "apple-generic";
 				VERSION_INFO_PREFIX = "";
 			};
@@ -2935,7 +2924,6 @@
 		1EB617561B0A30480035A986 /* ReleaseCrashOnly */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
-				"ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
 				CLANG_CXX_LIBRARY = "libc++";
 				CLANG_ENABLE_MODULES = YES;
@@ -2977,7 +2965,6 @@
 				SKIP_INSTALL = YES;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VALIDATE_PRODUCT = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				VERSIONING_SYSTEM = "apple-generic";
 				VERSION_INFO_PREFIX = "";
 			};
@@ -3049,7 +3036,6 @@
 				PRODUCT_BUNDLE_IDENTIFIER = "net.hockeyapp.$(PRODUCT_NAME:rfc1034identifier)";
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HockeySDK TestTarget.app/HockeySDK TestTarget";
-				VALID_ARCHS = "armv7 arm64";
 			};
 			name = Debug;
 		};
@@ -3115,7 +3101,6 @@
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HockeySDK TestTarget.app/HockeySDK TestTarget";
 				VALIDATE_PRODUCT = YES;
-				VALID_ARCHS = "armv7 arm64";
 			};
 			name = ReleaseDefault;
 		};
@@ -3181,7 +3166,6 @@
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HockeySDK TestTarget.app/HockeySDK TestTarget";
 				VALIDATE_PRODUCT = YES;
-				VALID_ARCHS = "armv7 arm64";
 			};
 			name = ReleaseCrashOnly;
 		};
@@ -3480,7 +3464,6 @@
 				PRODUCT_NAME = HockeySDK;
 				PUBLIC_HEADERS_FOLDER_PATH = "include/$(PRODUCT_NAME)";
 				SKIP_INSTALL = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				WATCHOS_DEPLOYMENT_TARGET = 2.0;
 			};
 			name = ReleaseFeedbackOnly;
@@ -3562,7 +3545,6 @@
 		B22DFC051FC750FF0052AF19 /* ReleaseFeedbackOnly */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
-				"ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
 				CLANG_CXX_LIBRARY = "libc++";
 				CLANG_ENABLE_MODULES = YES;
@@ -3605,7 +3587,6 @@
 				SKIP_INSTALL = YES;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VALIDATE_PRODUCT = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				VERSIONING_SYSTEM = "apple-generic";
 				VERSION_INFO_PREFIX = "";
 			};
@@ -3673,7 +3654,6 @@
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HockeySDK TestTarget.app/HockeySDK TestTarget";
 				VALIDATE_PRODUCT = YES;
-				VALID_ARCHS = "armv7 arm64";
 			};
 			name = ReleaseFeedbackOnly;
 		};
@@ -3764,7 +3744,6 @@
 				PRODUCT_NAME = HockeySDK;
 				PUBLIC_HEADERS_FOLDER_PATH = "include/$(PRODUCT_NAME)";
 				SKIP_INSTALL = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				WATCHOS_DEPLOYMENT_TARGET = 2.0;
 			};
 			name = Release;
@@ -3846,7 +3825,6 @@
 		B29855481D85EBC9007FF452 /* Release */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
-				"ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
 				CLANG_CXX_LIBRARY = "libc++";
 				CLANG_ENABLE_MODULES = YES;
@@ -3888,7 +3866,6 @@
 				SKIP_INSTALL = YES;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VALIDATE_PRODUCT = YES;
-				"VALID_ARCHS[sdk=iphonesimulator*]" = "$(BIT_SIM_ARCHS)";
 				VERSIONING_SYSTEM = "apple-generic";
 				VERSION_INFO_PREFIX = "";
 			};
@@ -3956,7 +3933,6 @@
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HockeySDK TestTarget.app/HockeySDK TestTarget";
 				VALIDATE_PRODUCT = YES;
-				VALID_ARCHS = "armv7 arm64";
 			};
 			name = Release;
 		};
diff --git a/Support/HockeySDKBase.xcconfig b/Support/HockeySDKBase.xcconfig
index 892cd86..2cd70ac 100644
--- a/Support/HockeySDKBase.xcconfig
+++ b/Support/HockeySDKBase.xcconfig
@@ -1,12 +1,6 @@
 BUILD_NUMBER = 110
 VERSION_STRING = 5.1.4
 GCC_PREPROCESSOR_DEFINITIONS = $(inherited) $(HOCKEYSDK_GCC_PREPROCESSOR_DEFINITIONS) HOCKEYSDK_CONFIGURATION_$(CONFIGURATION) BITHOCKEY_VERSION="@\""$(VERSION_STRING)"\"" BITHOCKEY_BUILD="@\""$(BUILD_NUMBER)"\"" BITHOCKEY_C_VERSION="\""$(VERSION_STRING)"\"" BITHOCKEY_C_BUILD="\""$(BUILD_NUMBER)"\""
-BIT_ARM_ARCHS = armv7 armv7s arm64
-BIT_SIM_ARCHS = x86_64 i386
-ARCHS[sdk=iphoneos*] = $(BIT_ARM_ARCHS)
-ARCHS[sdk=iphonesimulator*] = $(BIT_SIM_ARCHS)
-VALID_ARCHS[sdk=iphoneos*] = $(BIT_ARM_ARCHS)
-VALID_ARCHS[sdk=iphonesimulator*] = $(BIT_SIM_ARCHS)
 OTHER_CFLAGS = $(HOCKEYSDK_WARNING_FLAGS)
 OTHER_CFLAGS[sdk=iphoneos9.*] = $(HOCKEYSDK_WARNING_FLAGS) -fembed-bitcode
 OTHER_CFLAGS[sdk=iphonesimulator9.*] = $(HOCKEYSDK_WARNING_FLAGS) -fembed-bitcode-marker
```
</details>

After this, the definition of `ARCHS` becomes `$(ARCHS_STANDARD)`.

That gets things compiling, I don't know enough to say that keeps everything working for everyone at runtime — but it's compiling.

**Comment by Igor-Palaguta** [comment] 2019-03-25 10:47
@jdhealy thanks! This worked

**Comment by olegdanu-newstore** [comment] 2019-03-26 11:28
What about the official fix? Do you guys have any plan about it? @MatkovIvan @Jamminroot ?

**Comment by vol24pl** [comment] 2019-03-26 14:58
Same issue here. As Swift 5 and Xcode 10.2 are out of beta, this will quickly become a major concern.

**Comment by thonydam** [comment] 2019-03-26 22:38
We are experiencing the same issue since Xcode 10.2.

**Comment by vol24pl** [comment] 2019-03-28 22:38
My fork with applied diff from: https://github.com/bitstadium/HockeySDK-iOS/issues/548#issuecomment-475719680

https://github.com/vol24pl/HockeySDK-iOS

Use at your own risk, no guarantees!

**Comment by chriscombs** [comment] 2019-03-29 13:55
Any updates? Hockey SDK can't currently be used with Carthage when running Xcode 10.2

**Comment by PaulEhrhardt** [comment] 2019-04-01 13:28
Hey guys any updates on this bug?

**Comment by elamalani** [comment] 2019-04-01 21:07
Hey everyone, this is a known issue and we are going to work on a fix soon. I'll keep this thread posted once I have an update. Thank you.

**Comment by metasmile** [comment] 2019-04-10 12:02
Any updates?

**Comment by elamalani** [comment] 2019-04-10 17:24
Thank you all for your patience. We are actively working on a fix and will share an update on this thread once the issue is resolved.

**Comment by DuoBrian** [comment] 2019-04-11 20:23
FWIW, this got things working for me: https://github.com/bitstadium/HockeySDK-iOS/pull/550

**Comment by jcislinsky** [comment] 2019-04-15 12:54
@elamalani Do you have any estimation for the fix?

**Comment by odanu** [comment] 2019-04-22 13:52
Looks like this PR, is intended to fix the issues: https://github.com/bitstadium/HockeySDK-iOS/pull/553

**Comment by ghost** [comment] 2019-04-23 14:44
Any ETA on when you guys gonna make a new release with the fix?

**Comment by Jamminroot** [comment] 2019-04-24 09:03
Hey, @avolovoy, unfortunatelly I don't have any ETA. But, as @odanu pointed out, PR#553 seem to be fixing the issue, so you can track this one or checkout from a PR branch to get things working for you even before PR gets merged.

**Comment by Jamminroot** [comment] 2019-04-24 10:46
Origin of problem seem to be in dsymutil in carthage itself.
Though removing `armv7s` architecture is a valid fix, it can be a breaking change for customers who specify this architecture explicitly. 
Carthage uses the dynamic framework target only.

Another way to fix the bug is running dsymutil with verbose [logging ON](https://github.com/Carthage/Carthage/blob/0b66cef4046a196cf04f39877b541f7102725e80/Source/CarthageKit/Xcode.swift#L839), which for some reason also fixes the issue.

I've addressed ETA request to PM. I'll update you guys once I get the information.

**Comment by juan-marin** [comment] 2019-04-24 21:55
I just changed and installed HockeySDK via cocoapods and that worked out

**Comment by ghost** [comment] 2019-04-26 13:02
Just reminder that this issue is holding upgrades to swift 5 and its been more than 6 weeks from the date reported.

**Comment by metasmile** [comment] 2019-04-29 09:10
1 Month was gone. What is happening for your internal release schedule? 🤷‍♂

**Comment by thonydam** [comment] 2019-04-29 15:25
Hockeyapp is going away, I doubt there will be good maintenance happening in the next few months. We are planning to remove this dependency pretty soon from our CI and apps.

**Comment by elamalani** [comment] 2019-05-16 18:29
Hey everyone, 

I'm extremely sorry for the delayed response on this thread. Our team started looking at this issue few weeks back but had to delay the work because of other priorities. 

**Investigation result**

Based on our investigation, we found out that it's **not** an issue with the HockeySDK. The issue is happening in the `dsymutil` tool used by Carthage. The tool links the DWARF debug information found in the object files of the HockeySDK executable. 

There are 5 architectures in the HockeySDK executable - armv7, armv7s, arm64, x86_64, i386. As some of you mentioned, removing any one of these architectures solves the `dsymutil` issue. But removing an architecture in HockeySDK while the bug is in reality located in the `dsymutil` tool used by Carthage is just eluding the issue away from the HockeySDK framework while other third party frameworks are affected by the same issue. Plus, some integrations might still explicitly support the missing architecture and it would be a breaking change for them. 

 A solution to solve the issue on Carthage directly would benefit any framework in the same situation. By digging a bit deeper, we found that adding some options to the `dsymutil` command (i.e. `-verbose` or `-num-threads`) also solves the issue while preserving all 5 architectures. 
 
**Next steps**

There is already an issue opened on [Carthage](https://github.com/Carthage/Carthage/issues/2738) and we have commented on the same issue to let the Carthage repo owners know that the HockeySDK doesn't work with Xcode 10.2. Once the issue is resolved at their end, HockeySDK will start compiling using Xcode 10.2. 

 Please let us know if you have any questions.

**Closed as completed** 2020-02-19 14:09 UTC
Labels: bug
