### ISSUE TITLE
SDK logging an error instead of a debug or verbose message "The file “Application Support” doesn’t exist."

### ISSUE THREAD

**Issue by NickGaens** [bitstadium/HockeySDK-iOS#510] opened 2018-03-08 14:22 UTC
Xcode 9.3 beta 4, HockeySDK-iOS (v5.1.2) via CocoaPods.

When running my app (on either a simulator or a device), the following error message shows up in the console:

> [HockeySDK] void bit_fixBackupAttributeForURL(NSURL *__strong)_block_invoke/177 ERROR: Error while setting resource value: The file “Application Support” doesn’t exist.

**Comment by dhei** [comment] 2018-03-08 20:49
Hey @NickGaens,

Thanks for getting in touch. I am not aware of any known issue related to this. What is the iOS version are you targeting? Can you share the detailed error logs or crash report of this issue?

**Comment by NickGaens** [comment] 2018-03-09 10:17
Targeting iOS 11.0.

It's not an actual app crash, but rather a runtime error thrown out by the HockeySDK. If I add an 'halt on all exceptions breakpoint' in Xcode, it catches this error and pauses on the line
class AppDelegate: UIResponder, UIApplicationDelegate {

**Comment by TroubleMakerBen** [comment] 2018-03-12 22:45
Hi @NickGaens,

sorry for any confusion this has already caused you. This is actually a harmless message that should not be logged with the "error" label but as a debug information.
This will be fixed in the next version of the SDK.

Best,
Benjamin

PS: The logic for this is [in this method](https://github.com/bitstadium/HockeySDK-iOS/blob/797fd0669ad2852625cd904427390f88f9980808/Classes/BITHockeyHelper.m#L177).

**Comment by leearmstrong** [comment] 2018-06-29 09:19
When will this be addressed?

**Comment by ElektrojungeAtWork** [comment] 2018-10-10 16:58
This was fixed in version 5.1.4, closing this issue.

**Comment by rudagaras** [comment] 2018-10-24 15:10
Xcode 10.0 (10A255), HockeySDK-iOS (v5.1.4) via CocoaPods.

Hi, I'm getting the same error with this new version, what can I do?

[HockeySDK] -[BITCrashManager startManager]_block_invoke/1202 [HockeySDK] WARNING: Detecting crashes is NOT enabled due to running the app with a debugger attached.

[HockeySDK] void bit_fixBackupAttributeForURL(NSURL *__strong)_block_invoke/177 ERROR: Error while setting resource value: The file “Application Support” doesn’t exist.

**Comment by ElektrojungeAtWork** [comment] 2018-10-24 17:23
`[HockeySDK] -[BITCrashManager startManager]_block_invoke/1202 [HockeySDK] WARNING: Detecting crashes is NOT enabled due to running the app with a debugger attached.` is not an error, it means that you the HockeySDK cannot detect crashes because a debugger is attached. This is a limitation imposed on 3rd party crash reporters by iOS and Xcode.

`[HockeySDK] void bit_fixBackupAttributeForURL(NSURL *__strong)_block_invoke/177 ERROR: Error while setting resource value: The file “Application Support” doesn’t exist.`

This was supposed to be fixed. As described above, there is nothing for you to do and there are no side effects other than the message being off the wrong log level type.

I'm reopening the issue.

**Comment by ElektrojungeAtWork** [comment] 2018-10-24 17:25
FYI I renamed the issue to better reflect what it is about.

**Comment by guperrot** [comment] 2018-10-24 17:58
Do you have

```
[HockeySDK] void bit_fixBackupAttributeForURL(NSURL *__strong)_block_invoke/177 ERROR: Error while setting resource value: The file “Application Support” doesn’t exist.
```

Only on the first launch of the app?

**Comment by rudagaras** [comment] 2018-10-24 18:55
yes, just the firs time

**Comment by guperrot** [comment] 2018-10-24 19:09
Then yes I can confirm the issue is harmless and should be a debug log saying we are creating a file for the first time.

**Comment by inPhilly** [comment] 2019-04-25 01:25
I am still getting the error in the latest version

**Comment by Jamminroot** [comment] 2019-04-25 10:27
Hey, @inPhilly, can you provide some more context on this? Which exactly? The one mentioned in the beginning of a thread, or [this ](https://github.com/bitstadium/HockeySDK-iOS/issues/510/#issuecomment-432699165) one?

**Comment by Jamminroot** [comment] 2019-04-29 13:29
Hi, @inPhilly, just a friendly ping here.
Wanted you to know that fix with changed log level is [merged](https://github.com/bitstadium/HockeySDK-iOS/pull/537/), but not released yet; As for the initial question - it is just a harmless message, and you can just ignore it.

**Closed** 2020-02-19 14:09 UTC
Labels: bug
