### ISSUE TITLE
Here is why it is empty ？？

### ISSUE THREAD

**Issue by PyXXX** [bitstadium/HockeySDK-iOS#389] opened 2017-01-06 09:58 UTC
Sometimes the data is so obtained？

endTime = 1483696370249;
    exception =     {
        cause = "";      Here is why it is empty ？？
        name = "";       Here is why it is empty ？？
        signalInfo =         {
            faultAddress = "0x1176E8DD6 0 + 4688088534";
            signalCode = "#0";
            signalName = SIGABRT;
        };
    };

**Comment by TroubleMakerBen** [comment] 2017-01-06 18:06
Hey @PyXXX,

The exception name is not guaranteed to be available at all times as there are other causes for a crash than an exception. That said, it's pretty hard to guess what you are actually asking or what issue you are running into. Can you provide more information?

Best,
Benjamin

**Comment by PyXXX** [comment] 2017-01-09 03:05
Hey @TroubleMakerBen 

Stack:
    {"name":"","cause":"","signalInfo":{"signalCode":"TRAP_TRACE","signalName":"SIGTRAP","faultAddress":"0x104145D3D 0 + 4363410749"}}

No other more information, and only this, it looks good strange

**Comment by TroubleMakerBen** [comment] 2017-01-10 18:18
Hey @PyXXX,

Your data just confirms what I was writing. The crash you are seeing is not caused by an exception. To familiarize yourself with crashes on iOS, I recommend [our knowledgebase](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/which-types-of-crashes-can-be-collected-on-ios-and-os-x).
Other than that, I still don't understand what you are expecting me to do. Some more text and full sentences would help a lot ;)

Best,
Benny

**Comment by elektrojunge** [comment] 2017-01-17 17:22
I'm closing this as I can't help with the little info that was provided.
Feel free to open this issue again but please make sure to provide more context.

Best,
Benny

**Closed by elektrojunge** 2017-01-17 17:22 UTC
