### ISSUE TITLE
Upgrades showing as crashes

### ISSUE THREAD

**Issue by mtoon** [bitstadium/HockeySDK-iOS#264] opened 2016-03-08 11:44 UTC
It seems like we're getting this "crash" whenever a new build is installed via the in-app new version available popover.

Not a huge deal and could be possibly ignored, but if there was an easy way to identify these as non-crashes would be nice.

Thanks!

<img width="740" alt="screen shot 2016-03-08 at 6 41 46 am" src="https://cloud.githubusercontent.com/assets/802418/13600742/f1e942b8-e4f8-11e5-8984-a8889f485771.png">

**Comment by anlinde** [comment] 2016-03-08 12:20
Hi,

I assume you are not using an up to date SDK and did enable the property `enableAppNotTerminatingCleanlyDetection `. There was a bug in our SDK until version 3.7.2 and was fixed in this commit https://github.com/bitstadium/HockeySDK-iOS/commit/64aaf2aa8cb5d64d0b7599a48b95624d6fc234aa

Please update to the latest SDK and check again

Best,
Andreas

**Comment by mtoon** [comment] 2016-03-08 14:09
Hi!  We are using 3.8.5...  I noticed the crashes showing up with the last few builds (which is when we enabled the flag), but this last update was the first time I realized it was associated with the upgrade.   I will test on various devices when I push the next build just to make sure it is associated with the upgrade.

Thanks!
-m

**Comment by lumaxis** [comment] 2016-03-11 12:53
@mtoon I couldn't reproduce this behavior in my tests unfortunately. Just to make sure, I added another call to make sure we properly persist the flag indicating that the app exited because of an update in https://github.com/bitstadium/HockeySDK-iOS/commit/bfb9101ca8a71bb0f4bd4a9036e61df04fc73b2d
Please let me know if you find out any more details how/when this happens!

**Comment by mtoon** [comment] 2016-03-29 13:54
@lumaxis Sorry about the slow response.. not getting notifications from Github..   Appreciate it!  Looks like it might still be happening in 3.8.5, but can't narrow down.  It's random, but I'll keep trying to figure out how/when/why.  Thanks again!

**Comment by lumaxis** [comment] 2016-04-14 12:42
We've had another report of this issue so I'll try to investigate once more :mag:

**Comment by TroubleMakerBen** [comment] 2018-02-22 18:56
I'm closing this issue as it's almost 2 years old. Please feel free if you still have that issue.

Best,
Benjamin

**Closed by TroubleMakerBen** 2018-02-22 18:56 UTC
Labels: needs reproduction
