### ISSUE TITLE
XCode 8.1 - Compile error 

### ISSUE THREAD

**Issue by DAOCUONG** [bitstadium/HockeySDK-iOS#365] opened 2016-10-31 16:12 UTC
Try using pod 'HockeySDK' or pod 'HockeySDK-Source'
Got error with Xcode 8.1

...../Build/Products/Debug-iphonesimulator/HockeySDKResources.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1
Works fine with xcode 8.0.
Have tried remove Pods, delete Derived folder, clean , pod install no luck 

Reference https://forums.developer.apple.com/message/191903#191903

**Comment by TroubleMakerBen** [comment] 2016-10-31 16:22
Hi @DAOCUONG 

This is a duplicate of [#363](https://github.com/bitstadium/HockeySDK-iOS/issues/363) and updating cocoapods to `1.1.1` solves this issue.

**Comment by DAOCUONG** [comment] 2016-10-31 16:24
Thanks Ben

**Closed** 2016-10-31 16:24 UTC
