### ISSUE TITLE
Property 'authenticator' not found on object of type 'BITHockeyManager * 

### ISSUE THREAD

**Issue by SatishMavani** [bitstadium/HockeySDK-iOS#452] opened 2017-08-31 12:00 UTC
I am using Xcode 9 beta 6.

I have an older version of hockey app integrated into my project, so I deleted the HockeySDK.framework and HockeySDKResources.bundle package from my project.

Then I open hockey app on my Mac and select the same project to integrate hockey sdk again I follow the steps till dragging framework to my project and works fine till now.

Then there is a step which asks to run the project to initialize SDK, here when i run the project i am facing below error :

**Property 'authenticator' not found on object of type 'BITHockeyManager ***

**Comment by bmourat** [comment] 2017-09-05 12:48
Hi @SatishMavani 

I've checked integration process with HockeyApp for Mac and Xcode 8 and Xcode 9 beta 6 and could not reproduce this issue. So i will need additional info on this. 
1. What version of HockeySDK you were using before?


Best
Murat

**Comment by bmourat** [comment] 2017-09-05 13:04
Hi @SatishMavani

I've checked integration process with HockeyApp for Mac and Xcode 8 and Xcode 9 beta 6 and could not reproduce this issue. So i will need additional info on this. Could you check if there is HockeySDK.framework in your target's Linked frameworks and Libraries section. There is a bug in XCode 9, it doesn't automatically add frameworks to this section, when they are drag and dropped. If HockeySDK.framework is present, could you please answer this questions:

1. What version of HockeySDK you were using before?
2. Did you try this in XCode 8?
3. Can you share you HockeySDK setup code?
4. Have you tried manually integrating latest version of sdk?

Best
Murat

**Comment by TroubleMakerBen** [comment] 2017-09-15 07:43
I'm closing this issue as we're not able to reproduce the issue and we haven't heard from you in two weeks!
Feel free to open this issue again, if you continue to see issues.

Thx for using HockeyApp!
Benny

**Closed by TroubleMakerBen** 2017-09-15 07:43 UTC
Labels: needs reproduction

**Comment by lvandal** [comment] 2018-01-31 19:14
Probably too late but check your target's Framework Search Paths. It's probably including paths to HockeySDK you don't need. Had the same issue.

**Comment by TroubleMakerBen** [comment] 2018-02-01 20:23
@lvandal thx for the suggestion! Thx for using HockeyApp!
