### ISSUE TITLE
AssetsLibrary is integrated in the default Pod but not used

### ISSUE THREAD

**Issue by tschob** [bitstadium/HockeySDK-iOS#402] opened 2017-03-02 11:41 UTC
I'm currently investigating a missing photos permissions error during an app store submission. I can't find any suspicious content besides the `AssetsLibrary`. You currently integrate it in the default Pod. But it doesn't seem to be used - except in the BITFeedbackManager which is only included in the AllFeatures Spec.

Is there a reasons for the `AssetsLibrary` I missed?

**Comment by TroubleMakerBen** [comment] 2017-03-03 20:40
Hey Hans,

Thx for getting in touch. I agree that the AssetsLibrary doesn't need to be in the default configuration of the SDK.

You are the first one to report this issue, can you confirm with 100% certainty that the HockeySDK is the cause for it?

Please let me know ASAP so we can fix the issue in case HA is the cause for this.

Best,
Benny

**Comment by TroubleMakerBen** [comment] 2017-03-16 17:56
This was changed in #403 and will be in the next update of the SDK. Unfortunately, I cannot give you an ETA for this.

**Comment by TroubleMakerBen** [comment] 2017-04-29 01:50
This was fixed in verison 4.1.5.

**Closed by TroubleMakerBen** 2017-04-29 01:50 UTC
